Repository ohouse-clone/ohouse_back, pull requests merged in 2022-09, with the labels that each got.

#24 Create store basic api swagger
  src/main/java/com/clone/ohouse/shop/board/ProductBoardApiController.java
  src/main/java/com/clone/ohouse/shop/board/domain/dto/ProductBoardResponseDto.java
  src/main/java/com/clone/ohouse/shop/board/domain/dto/ProductBoardSaveRequestDto.java
  src/main/java/com/clone/ohouse/shop/board/domain/dto/ProductBoardUpdateRequestDto.java
  src/main/java/com/clone/ohouse/shop/board/domain/dto/serializer/ByteParser.java
  src/test/java/com/clone/ohouse/shop/board/ProductBoardApiControllerTest.java
  src/test/java/com/clone/ohouse/shop/board/domain/ProductBoardServiceTest.java
Labels: feature

#27 test(test): test for issue
  src/main/java/com/clone/ohouse/shop/board/ProductBoardApiController.java
Labels: fixed

#33 User, Post, Comment POST API
  src/main/java/com/clone/ohouse/community/controller/CommentController.java
  src/main/java/com/clone/ohouse/community/controller/PostController.java
  src/main/java/com/clone/ohouse/community/controller/UserController.java
  src/main/java/com/clone/ohouse/community/dto/CommentDto.java
  src/main/java/com/clone/ohouse/community/dto/UserDto.java
  src/main/java/com/clone/ohouse/community/entity/Comment.java
  src/main/java/com/clone/ohouse/community/entity/Post.java
  src/main/java/com/clone/ohouse/community/entity/User.java
  src/main/java/com/clone/ohouse/community/repository/CommentRepository.java
  src/main/java/com/clone/ohouse/community/repository/PostRepository.java
  src/main/java/com/clone/ohouse/community/service/CommentService.java
  src/main/java/com/clone/ohouse/community/service/PostService.java
  src/main/java/com/clone/ohouse/community/service/UserService.java
  src/test/java/com/clone/ohouse/CommentTest.java
  src/test/java/com/clone/ohouse/PostTest.java
  src/test/java/com/clone/ohouse/UserTest.java
Labels: feature, fixed
